### PR TITLE
Custom action improvements

### PR DESCRIPTION
**Pull request by mtongnz**
Changes implemented:
- add script arguments for custom scripts
- toggle to override default menu action items with custom actions
- customizable icons for custom actions
- translations for all added elements

### CODE REVIEW

**Comment by scolcipitato** [comment]
I have made some changes to the code, fixing some stuff and making the code more in line with the already present style. I don't currently have much time to test it, so if you can give it a go it would be awesome, I have created a new branch for this.

**Comment by mtongnz** [comment]
I've done a very quick test.  I don't use it with VMs so haven't checked, but it seems to be working great for dockers.
The changes made all make sense and don't seem to cause any issues.  I note you also fixed an issue where I put the icon input in the wrong spot which I noticed about 10 minutes after the sending the PR.
The only thing that I'd love to fix is the "Force Update" button always shows.  I haven't had time to dig into where it gets it's info from.  I use compose for all my containers so it's possibly to do with that.  It's next on my list to do.

**Comment by scolcipitato** [comment]
> The only thing that I'd love to fix is the "Force Update" button always shows. I haven't had time to dig into where it gets it's info from. I use compose for all my containers so it's possibly to do with that. It's next on my list to do.

The update status is derived directly from the raw data from docker. There is an option to hide the update column, but I would not remove the option altogether, but I'll wait to merge if you want to make some changes.

**Comment by Tyree** [comment]
> The only thing that I'd love to fix is the "Force Update" button always shows. I haven't had time to dig into where it gets it's info from. I use compose for all my containers so it's possibly to do with that. It's next on my list to do.

This has nothing to do with using Compose. It's there for everyone. It just allows you to force a pull from the repo whether the auto check thinks there's an update or not.
If it just annoys you to be there, you can hide the link with CSS. :-D

**Comment by scolcipitato** [comment]
> If it just annoys you to be there, you can hide the link with CSS.

I don't know if we are talking about the same thing, but for clarity, there is an option to hide the update (and force update) column on the actual page.
What I think he is talking about is the update/force update button in the menu that opens up when you click on the folder. For this case, you can use the custom script to remove the option before it is rendered on the page.
[Here](https://github.com/scolcipitato/folder.view/blob/6dda34d3e41225ff7d11e0675aa75555567af567/dev/docker/events.js#L226) is the reference if you want to use it.

**Comment by Tyree** [comment]
> > If it just annoys you to be there, you can hide the link with CSS.
> 
> I don't know if we are talking about the same thing, but for clarity, there is an option to hide the update (and force update) column on the actual page. What I think he is talking about is the update/force update button in the menu that opens up when you click on the folder. For this case, you can use the custom script to remove the option before it is rendered on the page. [Here](https://github.com/scolcipitato/folder.view/blob/6dda34d3e41225ff7d11e0675aa75555567af567/dev/docker/events.js#L226) is the reference if you want to use it.

Ah okay. My mistake. I thought he was talking about the Force Update on each row of the update column. I'll see myself out... :-D

**Comment by mtongnz** [comment]
I was meaning the force update in the menu. I'll have a look at it over the next couple of days and see if I can see any obvious way to make it not show if there's no dockerman containers in the folder.

As a side note, the force update on each container is from the docker manager plugin. I've made mods to remove that force update & update buttons when the container isn't managed by dockerman and to fix how network info is displayed.

**Pull request merged**
